
version: "3.9"
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: wa_saas
      POSTGRES_USER: wa_user
      POSTGRES_PASSWORD: wa_pass
    ports: ["5432:5432"]
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]

  api:
    build: ./server
    env_file: .env
    depends_on: [db, redis]
    ports: ["8000:8000"]
    volumes:
      - ./server/chroma_db:/app/chroma_db

  web:
    build: ./frontend
    env_file: .env
    depends_on: [api]
    ports: ["5173:5173"]

volumes:
  db_data:
